datadog:
  site: "datadoghq.com"
  clusterName: "mew-ddot-cluster"
  apiKeyExistingSecret: "datadog-secret"
  clusterChecks:
    enabled: true
  orchestratorExplorer:
    enabled: true
  otelCollector:
    enabled: true
    ports:
      - containerPort: 4317
        hostPort: 4317
        name: "otel-grpc"
      - containerPort: 4318
        hostPort: 4318
        name: "otel-http"
