apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-otel
  name: node-otel
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-otel
  template:
    metadata:
      labels:
        app: node-otel
      # annotations:
      # ad.datadoghq.com/server.logs: >-
      #   [{
      #     "source": "nodejs",
      #     "service": node-otel",
      #     "auto_multi_line_detection": true,
      #     "log_processing_rules": [{
      #       "type": "exclude_at_match",
      #       "name": "exclude_flushing_logs",
      #       "pattern" : "Flushing\\s+\\d+\\s+metrics\\s+via\\s+HTTP"
      #     }]
      #   }]
    spec:
      containers:
        - name: server
          image: mmeeww/node-otel:eef8344a8d5944f1ab32529f307b921da5ba7498
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_GRPC_PORT
              value: "4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):$(OTLP_GRPC_PORT)"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=node-otel,deployment.environment.name=staging"
            - name: OTEL_LOG_LEVEL
              value: "debug"

---
apiVersion: v1
kind: Service
metadata:
  name: node-otel
spec:
  selector:
    app: node-otel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
